server:
  port: 8081

spring:
  application:
    name: lessons

  datasource:
    url: jdbc:postgresql://localhost:5432/TestBackend
    username: postgres
    password: 1234567890

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always